services:
  - type: web
    name: the-bridge-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATA_ROOT
        value: /tmp/WebMainData
    healthCheckPath: /health 